# **SUBEMOTION**

In [ ]:
import gensim
import pandas as pd

In [ ]:
def readn(r,c):
  global em
  df = pd.read_fwf(r,lines=True)
  sh=df.shape
  print(df.columns)
  df[c] = df[c].astype(str)
  em = df[c].apply(gensim.utils.simple_preprocess)
  row = df[c].loc[0]
  return df,sh,em,row

In [ ]:
readn('/content/drive/MyDrive/OneFilePerEmotion/anger-NRC.txt','idiotic')

Index(['idiotic'], dtype='object')


(          idiotic
 0          offend
 1        strained
 2      punishment
 3         kicking
 4        hardened
 ...           ...
 14148     brigade
 14149   recurring
 14150  pharmacist
 14151      caress
 14152    humorous
 
 [14153 rows x 1 columns],
 (14153, 1),
 0            [offend]
 1          [strained]
 2        [punishment]
 3           [kicking]
 4          [hardened]
              ...     
 14148       [brigade]
 14149     [recurring]
 14150    [pharmacist]
 14151        [caress]
 14152      [humorous]
 Name: idiotic, Length: 14153, dtype: object,
 'offend')

In [ ]:
from gensim.models import Word2Vec
model = Word2Vec(window=10,min_count=1,workers=4)


In [ ]:
model.build_vocab(em)

In [ ]:
model.train(em, total_examples=model.corpus_count, epochs=model.epochs)

(70765, 70765)

In [ ]:
anger_sub = model.wv.vectors



In [ ]:
import numpy as np
print("Dimensions of 'data':", anger_sub.shape)

Dimensions of 'data': (14153, 100)


#AFFINITY PROPPAGATION **CLUSTERING**

In [ ]:
import numpy as np
from sklearn.cluster import AffinityPropagation

def cluster(a):
    clustering = AffinityPropagation().fit(a)
    labels = clustering.labels_

    n_clusters = len(np.unique(labels))
    cluster_data = []

    for cluster_label in range(n_clusters):
        cluster_points = a[labels == cluster_label]
        cluster_data.append(cluster_points)

    synthetic_data = []

    for cluster_points in cluster_data:
        num_samples = len(cluster_points)
        indices = np.random.choice(cluster_points.shape[0], size=num_samples, replace=True)
        synthetic_points = cluster_points[indices]
        synthetic_data.append(synthetic_points)

    n_clusters = len(np.unique(labels))
    print("Number of clusters:", n_clusters)
    return

In [ ]:
cluster(anger_sub)

Number of clusters: 542


# **subemotion**

In [ ]:
import numpy as np
from sklearn.cluster import AffinityPropagation
import pickle

def calculate_averages(data):
    clustering = AffinityPropagation().fit(data)
    labels = clustering.labels_

    n_clusters = len(np.unique(labels))
    cluster_averages = []

    for cluster_label in np.unique(labels):
        cluster_examples = data[labels == cluster_label]
        cluster_average = np.mean(cluster_examples, axis=0)
        cluster_averages.append(cluster_average)

    return np.array(cluster_averages)

def save_averages_to_file(averages_variable, output_filename):
    # Save all cluster averages to a .npy file
    np.save(output_filename, averages_variable)
    print("Saved all cluster averages to:", output_filename)

 # Print the dimensions of the saved file
    loaded_data = np.load(output_filename)
    print("Dimensions of saved file:", loaded_data.shape)
    # Print the variable name
    print("Variable name: averages_variable")

    return averages_variable  # Return the variable containing cluster averages



In [ ]:
anger_sub = model.wv.vectors
output_filename = 'anger.npy'
averages_variable = calculate_averages(anger_sub)
save_averages_to_file(averages_variable, output_filename)

Saved all cluster averages to: anger.npy
Dimensions of saved file: (542, 100)
Variable name: averages_variable


array([[ 7.0596070e-05, -2.6945258e-04,  2.7066059e-04, ...,
        -9.3088759e-04, -3.9556138e-03, -4.2638561e-04],
       [ 1.1071936e-03, -2.9571690e-03, -2.4674155e-03, ...,
        -1.1541145e-03, -5.7248533e-04,  1.4917430e-03],
       [-1.8210837e-03,  3.2488401e-03, -4.4884615e-05, ...,
        -1.6294182e-03, -1.8003576e-03,  1.9880701e-03],
       ...,
       [ 1.4439222e-04,  3.0816845e-03,  1.4967738e-03, ...,
        -4.1896682e-03, -2.8518718e-03,  1.0166666e-03],
       [-1.3026947e-03,  8.6840772e-04, -1.0419923e-03, ...,
         7.2436163e-04, -3.3549475e-03,  2.6798151e-03],
       [-1.9229843e-03, -1.8267079e-03,  2.3342897e-03, ...,
        -2.1493318e-03, -2.5495868e-03, -1.8950447e-03]], dtype=float32)

In [ ]:
import numpy as np

# Load the .npy file
npy_filename = '/content/anger.npy'
loaded_array = np.load(npy_filename)

# Print the dimensions of the loaded array
print("Dimensions of", npy_filename + ":", loaded_array.shape)

Dimensions of /content/anger.npy: (542, 100)


# **anticipation**

In [ ]:
readn('/content/drive/MyDrive/OneFilePerEmotion/anticipation-NRC-Emotion-Lexicon.txt','worry')

Index(['worry'], dtype='object')


(             worry
 0         threaten
 1           shiver
 2            youth
 3             hymn
 4       unverified
 ...            ...
 14148    theocracy
 14149        tacky
 14150  sensational
 14151         cusp
 14152       girdle
 
 [14153 rows x 1 columns],
 (14153, 1),
 0           [threaten]
 1             [shiver]
 2              [youth]
 3               [hymn]
 4         [unverified]
              ...      
 14148      [theocracy]
 14149          [tacky]
 14150    [sensational]
 14151           [cusp]
 14152         [girdle]
 Name: worry, Length: 14153, dtype: object,
 'threaten')

In [ ]:
from gensim.models import Word2Vec
model = Word2Vec(window=10,min_count=1,workers=4)

In [ ]:
model.build_vocab(em)

In [ ]:
model.train(em, total_examples=model.corpus_count, epochs=model.epochs)

(70765, 70765)

In [ ]:
anticipation_sub = model.wv.vectors

In [ ]:
import numpy as np
print("Dimensions of 'data':", anger_sub.shape)

Dimensions of 'data': (14153, 100)


In [ ]:
cluster(anticipation_sub)

Number of clusters: 541


In [ ]:
anticipation_sub = model.wv.vectors
output_filename = 'anticipation.npy'
averages_variable = calculate_averages(anticipation_sub)
save_averages_to_file(averages_variable, output_filename)

Saved all cluster averages to: anticipation.npy
Dimensions of saved file: (541, 100)
Variable name: averages_variable


array([[ 7.0596070e-05, -2.6945258e-04,  2.7066059e-04, ...,
        -9.3088759e-04, -3.9556138e-03, -4.2638561e-04],
       [ 1.1071936e-03, -2.9571690e-03, -2.4674155e-03, ...,
        -1.1541145e-03, -5.7248533e-04,  1.4917430e-03],
       [-1.8210837e-03,  3.2488401e-03, -4.4884615e-05, ...,
        -1.6294182e-03, -1.8003576e-03,  1.9880701e-03],
       ...,
       [ 6.2298705e-04, -3.0395510e-03,  4.3446227e-05, ...,
        -1.1598982e-04, -1.4794441e-03, -7.3997013e-04],
       [ 1.4439222e-04,  3.0816845e-03,  1.4967738e-03, ...,
        -4.1896682e-03, -2.8518718e-03,  1.0166666e-03],
       [-1.6719603e-03,  8.6274929e-04, -6.3074136e-04, ...,
         4.6999188e-04, -3.5768317e-03,  2.4774389e-03]], dtype=float32)

# **DISGUST**

In [ ]:
readn('/content/drive/MyDrive/OneFilePerEmotion/disgust-NRC-Emotion-Lexicon.txt','disobedience')


Index(['disobedience'], dtype='object')


(        disobedience
 0             maggot
 1           betrayal
 2         ungrateful
 3           quagmire
 4            pungent
 ...              ...
 14148       approval
 14149   acquisitions
 14150        repress
 14151  sequestration
 14152        lyrical
 
 [14153 rows x 1 columns],
 (14153, 1),
 0               [maggot]
 1             [betrayal]
 2           [ungrateful]
 3             [quagmire]
 4              [pungent]
               ...       
 14148         [approval]
 14149     [acquisitions]
 14150          [repress]
 14151    [sequestration]
 14152          [lyrical]
 Name: disobedience, Length: 14153, dtype: object,
 'maggot')

In [ ]:
from gensim.models import Word2Vec
model = Word2Vec(window=10,min_count=1,workers=4)

In [ ]:
model.build_vocab(em)

In [ ]:
model.train(em, total_examples=model.corpus_count, epochs=model.epochs)

(70765, 70765)

In [ ]:
disgust_sub = model.wv.vectors

In [ ]:
import numpy as np
print("Dimensions of 'data':", anger_sub.shape)

Dimensions of 'data': (14153, 100)


In [ ]:
cluster(disgust_sub)

Number of clusters: 540


In [ ]:
disgust_sub = model.wv.vectors
output_filename = 'disgust.npy'
averages_variable = calculate_averages(disgust_sub)
save_averages_to_file(averages_variable, output_filename)

Saved all cluster averages to: disgust.npy
Dimensions of saved file: (540, 100)
Variable name: averages_variable


array([[ 7.0596070e-05, -2.6945258e-04,  2.7066059e-04, ...,
        -9.3088759e-04, -3.9556138e-03, -4.2638561e-04],
       [ 1.1071936e-03, -2.9571690e-03, -2.4674155e-03, ...,
        -1.1541145e-03, -5.7248533e-04,  1.4917430e-03],
       [-1.8210837e-03,  3.2488401e-03, -4.4884615e-05, ...,
        -1.6294182e-03, -1.8003576e-03,  1.9880701e-03],
       ...,
       [ 1.4439222e-04,  3.0816845e-03,  1.4967738e-03, ...,
        -4.1896682e-03, -2.8518718e-03,  1.0166666e-03],
       [-1.6719603e-03,  8.6274929e-04, -6.3074136e-04, ...,
         4.6999188e-04, -3.5768317e-03,  2.4774389e-03],
       [-1.9229843e-03, -1.8267079e-03,  2.3342897e-03, ...,
        -2.1493318e-03, -2.5495868e-03, -1.8950447e-03]], dtype=float32)

# **fear**

In [ ]:
readn('/content/drive/MyDrive/OneFilePerEmotion/fear-NRC-Emotion-Lexicon.txt','parachute')

Index(['parachute'], dtype='object')


(         parachute
 0        horrified
 1         hopeless
 2         validity
 3             pare
 4        alertness
 ...            ...
 14148        gloss
 14149  altercation
 14150    occupying
 14151    stimulant
 14152     shilling
 
 [14153 rows x 1 columns],
 (14153, 1),
 0          [horrified]
 1           [hopeless]
 2           [validity]
 3               [pare]
 4          [alertness]
              ...      
 14148          [gloss]
 14149    [altercation]
 14150      [occupying]
 14151      [stimulant]
 14152       [shilling]
 Name: parachute, Length: 14153, dtype: object,
 'horrified')

In [ ]:
from gensim.models import Word2Vec
model = Word2Vec(window=10,min_count=1,workers=4)

In [ ]:
model.build_vocab(em)

In [ ]:
model.train(em, total_examples=model.corpus_count, epochs=model.epochs)

(70765, 70765)

In [ ]:
fear_sub = model.wv.vectors

In [ ]:
fear_sub= model.wv.vectors
output_filename = 'fear.npy'
averages_variable = calculate_averages(fear_sub)
save_averages_to_file(averages_variable, output_filename)

Saved all cluster averages to: fear.npy
Dimensions of saved file: (542, 100)
Variable name: averages_variable


array([[ 7.0596070e-05, -2.6945258e-04,  2.7066059e-04, ...,
        -9.3088759e-04, -3.9556138e-03, -4.2638561e-04],
       [ 1.1071936e-03, -2.9571690e-03, -2.4674155e-03, ...,
        -1.1541145e-03, -5.7248533e-04,  1.4917430e-03],
       [-1.8210837e-03,  3.2488401e-03, -4.4884615e-05, ...,
        -1.6294182e-03, -1.8003576e-03,  1.9880701e-03],
       ...,
       [ 1.4439222e-04,  3.0816845e-03,  1.4967738e-03, ...,
        -4.1896682e-03, -2.8518718e-03,  1.0166666e-03],
       [-1.3026947e-03,  8.6840772e-04, -1.0419923e-03, ...,
         7.2436163e-04, -3.3549475e-03,  2.6798151e-03],
       [-1.9229843e-03, -1.8267079e-03,  2.3342897e-03, ...,
        -2.1493318e-03, -2.5495868e-03, -1.8950447e-03]], dtype=float32)

# **joy**

In [ ]:
readn('/content/drive/MyDrive/OneFilePerEmotion/joy-NRC-Emotion-Lexicon.txt','angelic')

Index(['angelic'], dtype='object')


(           angelic
 0          jackpot
 1         pleasant
 2          amnesty
 3           aspire
 4           ardent
 ...            ...
 14148    bothering
 14149        broom
 14150  ineffectual
 14151    revolting
 14152          ham
 
 [14153 rows x 1 columns],
 (14153, 1),
 0            [jackpot]
 1           [pleasant]
 2            [amnesty]
 3             [aspire]
 4             [ardent]
              ...      
 14148      [bothering]
 14149          [broom]
 14150    [ineffectual]
 14151      [revolting]
 14152            [ham]
 Name: angelic, Length: 14153, dtype: object,
 'jackpot')

In [ ]:
from gensim.models import Word2Vec
model = Word2Vec(window=10,min_count=1,workers=4)

In [ ]:
model.build_vocab(em)

In [ ]:
model.train(em, total_examples=model.corpus_count, epochs=model.epochs)

(70765, 70765)

In [ ]:
joy_sub = model.wv.vectors

In [ ]:
cluster(joy_sub)

Number of clusters: 540


In [ ]:
joy_sub= model.wv.vectors
output_filename = 'joy.npy'
averages_variable = calculate_averages(joy_sub)
save_averages_to_file(averages_variable, output_filename)

Saved all cluster averages to: joy.npy
Dimensions of saved file: (540, 100)
Variable name: averages_variable


array([[ 7.0596070e-05, -2.6945258e-04,  2.7066059e-04, ...,
        -9.3088759e-04, -3.9556138e-03, -4.2638561e-04],
       [ 1.1071936e-03, -2.9571690e-03, -2.4674155e-03, ...,
        -1.1541145e-03, -5.7248533e-04,  1.4917430e-03],
       [-1.8210837e-03,  3.2488401e-03, -4.4884615e-05, ...,
        -1.6294182e-03, -1.8003576e-03,  1.9880701e-03],
       ...,
       [ 1.4439222e-04,  3.0816845e-03,  1.4967738e-03, ...,
        -4.1896682e-03, -2.8518718e-03,  1.0166666e-03],
       [-1.6719603e-03,  8.6274929e-04, -6.3074136e-04, ...,
         4.6999188e-04, -3.5768317e-03,  2.4774389e-03],
       [-1.9229843e-03, -1.8267079e-03,  2.3342897e-03, ...,
        -2.1493318e-03, -2.5495868e-03, -1.8950447e-03]], dtype=float32)

# **negative**

In [ ]:
readn('/content/drive/MyDrive/OneFilePerEmotion/negative-NRC-Emotion-Lexicon.txt','dementia')

Index(['dementia'], dtype='object')


(           dementia
 0       elimination
 1          pathetic
 2             lower
 3           gasping
 4             leech
 ...             ...
 14148      fruitful
 14149    locomotion
 14150  hydrographic
 14151     sculpture
 14152        plover
 
 [14153 rows x 1 columns],
 (14153, 1),
 0         [elimination]
 1            [pathetic]
 2               [lower]
 3             [gasping]
 4               [leech]
               ...      
 14148        [fruitful]
 14149      [locomotion]
 14150    [hydrographic]
 14151       [sculpture]
 14152          [plover]
 Name: dementia, Length: 14153, dtype: object,
 'elimination')

In [ ]:
from gensim.models import Word2Vec
model = Word2Vec(window=10,min_count=1,workers=4)

In [ ]:
model.build_vocab(em)

In [ ]:
model.train(em, total_examples=model.corpus_count, epochs=model.epochs)

(70715, 70715)

In [ ]:
negative_sub = model.wv.vectors

In [ ]:
cluster(negative_sub)

Number of clusters: 541


In [ ]:
negative_sub= model.wv.vectors
output_filename = 'negative.npy'
averages_variable = calculate_averages(negative_sub)
save_averages_to_file(averages_variable, output_filename)

Saved all cluster averages to: negative.npy
Dimensions of saved file: (541, 100)
Variable name: averages_variable


array([[ 7.0596070e-05, -2.6945258e-04,  2.7066059e-04, ...,
        -9.3088759e-04, -3.9556138e-03, -4.2638561e-04],
       [ 1.1071936e-03, -2.9571690e-03, -2.4674155e-03, ...,
        -1.1541145e-03, -5.7248533e-04,  1.4917430e-03],
       [-1.8210837e-03,  3.2488401e-03, -4.4884615e-05, ...,
        -1.6294182e-03, -1.8003576e-03,  1.9880701e-03],
       ...,
       [ 6.2298705e-04, -3.0395510e-03,  4.3446227e-05, ...,
        -1.1598982e-04, -1.4794441e-03, -7.3997013e-04],
       [ 1.4439222e-04,  3.0816845e-03,  1.4967738e-03, ...,
        -4.1896682e-03, -2.8518718e-03,  1.0166666e-03],
       [-1.6719603e-03,  8.6274929e-04, -6.3074136e-04, ...,
         4.6999188e-04, -3.5768317e-03,  2.4774389e-03]], dtype=float32)

# **positive**

In [ ]:
readn('/content/drive/MyDrive/OneFilePerEmotion/positive-NRC-Emotion-Lexicon.txt','forte')

Index(['forte'], dtype='object')


(           forte
 0        tribute
 1      anchorage
 2        pastime
 3        flowery
 4       athletic
 ...          ...
 14148   helpless
 14149       daze
 14150      smoky
 14151    crayons
 14152    foliage
 
 [14153 rows x 1 columns],
 (14153, 1),
 0          [tribute]
 1        [anchorage]
 2          [pastime]
 3          [flowery]
 4         [athletic]
             ...     
 14148     [helpless]
 14149         [daze]
 14150        [smoky]
 14151      [crayons]
 14152      [foliage]
 Name: forte, Length: 14153, dtype: object,
 'tribute')

In [ ]:
from gensim.models import Word2Vec
model = Word2Vec(window=10,min_count=1,workers=4)

In [ ]:
model.build_vocab(em)

In [ ]:
model.train(em, total_examples=model.corpus_count, epochs=model.epochs)

(70765, 70765)

In [ ]:
positive_sub = model.wv.vectors

In [ ]:
cluster( positive_sub)

Number of clusters: 541


In [ ]:
positive_sub= model.wv.vectors
output_filename = 'positive.npy'
averages_variable = calculate_averages(positive_sub)
save_averages_to_file(averages_variable, output_filename)

Saved all cluster averages to: positive.npy
Dimensions of saved file: (541, 100)
Variable name: averages_variable


array([[ 7.0596070e-05, -2.6945258e-04,  2.7066059e-04, ...,
        -9.3088759e-04, -3.9556138e-03, -4.2638561e-04],
       [ 1.1071936e-03, -2.9571690e-03, -2.4674155e-03, ...,
        -1.1541145e-03, -5.7248533e-04,  1.4917430e-03],
       [-1.8210837e-03,  3.2488401e-03, -4.4884615e-05, ...,
        -1.6294182e-03, -1.8003576e-03,  1.9880701e-03],
       ...,
       [ 6.2298705e-04, -3.0395510e-03,  4.3446227e-05, ...,
        -1.1598982e-04, -1.4794441e-03, -7.3997013e-04],
       [ 1.4439222e-04,  3.0816845e-03,  1.4967738e-03, ...,
        -4.1896682e-03, -2.8518718e-03,  1.0166666e-03],
       [-1.6719603e-03,  8.6274929e-04, -6.3074136e-04, ...,
         4.6999188e-04, -3.5768317e-03,  2.4774389e-03]], dtype=float32)

# **sadnesss**

In [ ]:
readn('/content/drive/MyDrive/OneFilePerEmotion/sadness-NRC-Emotion-Lexicon.txt','hydrocephalus')

Index(['hydrocephalus'], dtype='object')


(      hydrocephalus
 0        infliction
 1              dull
 2             cross
 3        disqualify
 4          collapse
 ...             ...
 14148     absorbent
 14149          swim
 14150     specially
 14151           bis
 14152          rope
 
 [14153 rows x 1 columns],
 (14153, 1),
 0        [infliction]
 1              [dull]
 2             [cross]
 3        [disqualify]
 4          [collapse]
              ...     
 14148     [absorbent]
 14149          [swim]
 14150     [specially]
 14151           [bis]
 14152          [rope]
 Name: hydrocephalus, Length: 14153, dtype: object,
 'infliction')

In [ ]:
from gensim.models import Word2Vec
model = Word2Vec(window=10,min_count=1,workers=4)

In [ ]:
model.build_vocab(em)

In [ ]:
model.train(em, total_examples=model.corpus_count, epochs=model.epochs)

(70765, 70765)

In [ ]:
sadness_sub = model.wv.vectors

In [ ]:
cluster( sadness_sub)

Number of clusters: 541


In [ ]:
sadness_sub= model.wv.vectors
output_filename = 'sadness.npy'
averages_variable = calculate_averages(sadness_sub)
save_averages_to_file(averages_variable, output_filename)

Saved all cluster averages to: sadness.npy
Dimensions of saved file: (541, 100)
Variable name: averages_variable


array([[ 7.0596070e-05, -2.6945258e-04,  2.7066059e-04, ...,
        -9.3088759e-04, -3.9556138e-03, -4.2638561e-04],
       [ 1.1071936e-03, -2.9571690e-03, -2.4674155e-03, ...,
        -1.1541145e-03, -5.7248533e-04,  1.4917430e-03],
       [-1.8210837e-03,  3.2488401e-03, -4.4884615e-05, ...,
        -1.6294182e-03, -1.8003576e-03,  1.9880701e-03],
       ...,
       [ 6.2298705e-04, -3.0395510e-03,  4.3446227e-05, ...,
        -1.1598982e-04, -1.4794441e-03, -7.3997013e-04],
       [ 1.4439222e-04,  3.0816845e-03,  1.4967738e-03, ...,
        -4.1896682e-03, -2.8518718e-03,  1.0166666e-03],
       [-1.6719603e-03,  8.6274929e-04, -6.3074136e-04, ...,
         4.6999188e-04, -3.5768317e-03,  2.4774389e-03]], dtype=float32)

# **surprise**

In [ ]:
readn('/content/drive/MyDrive/OneFilePerEmotion/surprise-NRC-Emotion-Lexicon.txt','gawk')

Index(['gawk'], dtype='object')


(                gawk
 0      improvisation
 1         excitation
 2            volcano
 3            cherish
 4            succeed
 ...              ...
 14148    coexistence
 14149    justifiable
 14150        beading
 14151      wherefore
 14152          bulky
 
 [14153 rows x 1 columns],
 (14153, 1),
 0        [improvisation]
 1           [excitation]
 2              [volcano]
 3              [cherish]
 4              [succeed]
               ...       
 14148      [coexistence]
 14149      [justifiable]
 14150          [beading]
 14151        [wherefore]
 14152            [bulky]
 Name: gawk, Length: 14153, dtype: object,
 'improvisation')

In [ ]:
from gensim.models import Word2Vec
model = Word2Vec(window=10,min_count=1,workers=4)

In [ ]:
model.build_vocab(em)

In [ ]:
model.train(em, total_examples=model.corpus_count, epochs=model.epochs)

(70765, 70765)

In [ ]:
surprise_sub = model.wv.vectors

In [ ]:
cluster(surprise_sub)

Number of clusters: 541


In [ ]:
surprise_sub= model.wv.vectors
output_filename = 'surprise.npy'
averages_variable = calculate_averages(surprise_sub)
save_averages_to_file(averages_variable, output_filename)

Saved all cluster averages to: surprise.npy
Dimensions of saved file: (541, 100)
Variable name: averages_variable


array([[ 7.0596070e-05, -2.6945258e-04,  2.7066059e-04, ...,
        -9.3088759e-04, -3.9556138e-03, -4.2638561e-04],
       [ 1.1071936e-03, -2.9571690e-03, -2.4674155e-03, ...,
        -1.1541145e-03, -5.7248533e-04,  1.4917430e-03],
       [-1.8210837e-03,  3.2488401e-03, -4.4884615e-05, ...,
        -1.6294182e-03, -1.8003576e-03,  1.9880701e-03],
       ...,
       [ 6.2298705e-04, -3.0395510e-03,  4.3446227e-05, ...,
        -1.1598982e-04, -1.4794441e-03, -7.3997013e-04],
       [ 1.4439222e-04,  3.0816845e-03,  1.4967738e-03, ...,
        -4.1896682e-03, -2.8518718e-03,  1.0166666e-03],
       [-1.6719603e-03,  8.6274929e-04, -6.3074136e-04, ...,
         4.6999188e-04, -3.5768317e-03,  2.4774389e-03]], dtype=float32)

# **trust**

In [ ]:
readn('/content/drive/MyDrive/OneFilePerEmotion/trust-NRC-Emotion-Lexicon.txt','judiciary')

Index(['judiciary'], dtype='object')


(        judiciary
 0         consort
 1         convent
 2        cautious
 3      management
 4             cap
 ...           ...
 14148     manager
 14149       plume
 14150        tilt
 14151      deduce
 14152        anal
 
 [14153 rows x 1 columns],
 (14153, 1),
 0           [consort]
 1           [convent]
 2          [cautious]
 3        [management]
 4               [cap]
              ...     
 14148       [manager]
 14149         [plume]
 14150          [tilt]
 14151        [deduce]
 14152          [anal]
 Name: judiciary, Length: 14153, dtype: object,
 'consort')

In [ ]:
from gensim.models import Word2Vec
model = Word2Vec(window=10,min_count=1,workers=4)

In [ ]:
model.build_vocab(em)

In [ ]:
model.train(em, total_examples=model.corpus_count, epochs=model.epochs)

(70765, 70765)

In [ ]:
trust_sub = model.wv.vectors

In [ ]:
cluster(trust_sub)

Number of clusters: 542


In [ ]:
trust_sub= model.wv.vectors
output_filename = 'trust.npy'
averages_variable = calculate_averages(trust_sub)
save_averages_to_file(averages_variable, output_filename)

Saved all cluster averages to: trust.npy
Dimensions of saved file: (542, 100)
Variable name: averages_variable


array([[ 7.0596070e-05, -2.6945258e-04,  2.7066059e-04, ...,
        -9.3088759e-04, -3.9556138e-03, -4.2638561e-04],
       [ 1.1071936e-03, -2.9571690e-03, -2.4674155e-03, ...,
        -1.1541145e-03, -5.7248533e-04,  1.4917430e-03],
       [-1.8210837e-03,  3.2488401e-03, -4.4884615e-05, ...,
        -1.6294182e-03, -1.8003576e-03,  1.9880701e-03],
       ...,
       [ 1.4439222e-04,  3.0816845e-03,  1.4967738e-03, ...,
        -4.1896682e-03, -2.8518718e-03,  1.0166666e-03],
       [-1.3026947e-03,  8.6840772e-04, -1.0419923e-03, ...,
         7.2436163e-04, -3.3549475e-03,  2.6798151e-03],
       [-1.9229843e-03, -1.8267079e-03,  2.3342897e-03, ...,
        -2.1493318e-03, -2.5495868e-03, -1.8950447e-03]], dtype=float32)

# **subemotion**

In [ ]:
import numpy as np

def append_npy_files(file1, file2,file3,file4,file5,file6,file7,file8,file9,file10, output_file):
    data1 = np.load(file1)
    data2 = np.load(file2)
    data3 = np.load(file3)
    data4 = np.load(file4)
    data5 = np.load(file5)
    data6 = np.load(file6)
    data7 = np.load(file7)
    data8 = np.load(file8)
    data9 = np.load(file9)
    data10 = np.load(file10)


    appended_data = np.concatenate((data1, data2,data3,data4,data5,data6,data7,data8,data9,data10), axis=0)

    np.save(output_file, appended_data)

if __name__ == "__main__":
    file1 = "/content/anger.npy"
    file2 = "/content/anticipation.npy"
    file3 = "/content/disgust.npy"
    file4 = "/content/fear.npy"
    file5 = "/content/joy.npy"
    file6 = "/content/negative.npy"
    file7 = "/content/positive.npy"
    file8 = "/content/sadness.npy"
    file9 = "/content/surprise.npy"
    file10 = "/content/trust.npy"
    output_file = "/content/subemotion_orginal.npy"

    append_npy_files(file1, file2,file3,file4,file5,file6,file7,file8,file9,file10, output_file)
    print("Files appended and saved to", output_file)


Files appended and saved to /content/subemotion_orginal.npy


In [ ]:
import numpy as np

# Specify the path to the .npy file
npy_file_path = '/content/subemotion_orginal.npy'

# Load the .npy file
loaded_array = np.load(npy_file_path)

# Print the dimensions of the loaded array
print("Dimensions of", npy_file_path + ":", loaded_array.shape)

Dimensions of /content/subemotion_orginal.npy: (5411, 100)
